# Configuration for BudgetWise Forecasting System

# Data settings
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  features_data_path: "data/features/"
  test_size: 0.2
  validation_size: 0.2
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

# Preprocessing settings
preprocessing:
  duplicate_threshold: 0.95
  outlier_method: "iqr"
  outlier_factor: 1.5
  date_formats: 
    - "%Y-%m-%d"
    - "%d-%m-%Y" 
    - "%m/%d/%Y"
    - "%d/%m/%Y"
  amount_patterns:
    - "₹\\s*([0-9,]+\\.?[0-9]*)"
    - "\\$\\s*([0-9,]+\\.?[0-9]*)" 
    - "([0-9,]+\\.?[0-9]*)"

# Feature engineering
features:
  lag_periods: [1, 7, 14, 30, 90]
  rolling_windows: [7, 14, 30, 60, 90]
  seasonal_periods: [7, 30, 365]
  
# Model configurations
models:
  baseline:
    linear_regression:
      fit_intercept: true
    arima:
      max_p: 5
      max_d: 2
      max_q: 5
      seasonal: true
    prophet:
      daily_seasonality: true
      weekly_seasonality: true
      yearly_seasonality: true
      
  machine_learning:
    random_forest:
      n_estimators: 100
      max_depth: 10
      random_state: 42
    xgboost:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      random_state: 42
    lightgbm:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      random_state: 42
      
  deep_learning:
    lstm:
      units: [64, 32, 16]
      dropout: 0.2
      sequence_length: 30
      batch_size: 32
      epochs: 100
      learning_rate: 0.001
    gru:
      units: [64, 32, 16]
      dropout: 0.2
      sequence_length: 30
      batch_size: 32
      epochs: 100
      learning_rate: 0.001

# Evaluation settings
evaluation:
  metrics: ["mae", "rmse", "mape", "directional_accuracy"]
  forecast_horizons: [1, 3, 6]  # months
  cross_validation_folds: 5

# Application settings
app:
  title: "BudgetWise: Personal Expense Forecasting"
  theme: "light"
  sidebar_width: 300
  chart_height: 400
  
# Logging
logging:
  level: "INFO"
  file: "logs/budgetwise.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"